/**
 * Correcciones curadas sobre la inferencia automática.
 *
 * `STAPLES` indica qué ejercicios prefiere el motor al elegir para cada patrón:
 *   3 = básico imprescindible, 2 = accesorio excelente, 1 = válido.
 * El resto de ejercicios de fuerza reciben 1 por defecto y los demás 0 (no se programan
 * automáticamente, pero están en la biblioteca y como alternativas).
 */
import type { Equipment, InjuryZone, Level, Muscle, Pattern, StressLevel } from '../../src/domain'

export const STAPLES: Record<string, 1 | 2 | 3> = {
  // Sentadilla
  'barbell-squat': 3,
  'front-barbell-squat': 2,
  'goblet-squat': 3,
  'leg-press': 3,
  'hack-squat': 2,
  'smith-machine-squat': 2,
  'bodyweight-squat': 3,
  'dumbbell-squat': 2,
  'box-squat': 1,
  'chair-squat': 1,
  // Bisagra de cadera
  'barbell-deadlift': 3,
  'romanian-deadlift': 3,
  'stiff-legged-dumbbell-deadlift': 3,
  'trap-bar-deadlift': 2,
  'sumo-deadlift': 2,
  'hyperextensions-back-extensions': 2,
  'one-arm-kettlebell-swings': 2,
  'kettlebell-one-legged-deadlift': 2,
  'good-morning': 1,
  'cable-deadlifts': 1,
  // Zancadas y unilaterales
  'dumbbell-lunges': 3,
  'split-squat-with-dumbbells': 3,
  'dumbbell-rear-lunge': 3,
  'bodyweight-walking-lunge': 2,
  'barbell-lunge': 2,
  'dumbbell-step-ups': 2,
  'elevated-back-lunge': 1,
  'barbell-walking-lunge': 1,
  // Extensión de cadera
  'barbell-hip-thrust': 3,
  'barbell-glute-bridge': 2,
  'butt-lift-bridge': 3,
  'single-leg-glute-bridge': 2,
  'one-legged-cable-kickback': 2,
  'pull-through': 2,
  'glute-kickback': 1,
  // Rodilla
  'leg-extensions': 3,
  'single-leg-leg-extension': 1,
  'lying-leg-curls': 3,
  'seated-leg-curl': 3,
  'standing-leg-curl': 2,
  'ball-leg-curl': 2,
  'natural-glute-ham-raise': 1,
  'glute-ham-raise': 1,
  // Gemelos, aductores y abductores
  'standing-calf-raises': 3,
  'seated-calf-raise': 3,
  'standing-dumbbell-calf-raise': 2,
  'calf-press-on-the-leg-press-machine': 2,
  'calf-raises-with-bands': 1,
  'dumbbell-seated-one-leg-calf-raise': 1,
  'smith-machine-calf-raise': 1,
  'thigh-abductor': 2,
  'thigh-adductor': 2,
  'cable-hip-adduction': 1,
  'band-hip-adductions': 1,
  // Empuje horizontal
  'barbell-bench-press-medium-grip': 3,
  'dumbbell-bench-press': 3,
  'incline-dumbbell-press': 3,
  'barbell-incline-bench-press-medium-grip': 3,
  pushups: 3,
  'incline-push-up': 2,
  'machine-bench-press': 2,
  'leverage-chest-press': 2,
  'leverage-incline-chest-press': 2,
  'smith-machine-incline-bench-press': 2,
  'close-grip-barbell-bench-press': 2,
  'smith-machine-bench-press': 1,
  'decline-barbell-bench-press': 1,
  'dumbbell-floor-press': 1,
  'cable-chest-press': 1,
  'push-ups-with-feet-elevated': 1,
  'push-up-wide': 1,
  'push-ups-close-triceps-position': 1,
  // Empuje vertical
  'dumbbell-shoulder-press': 3,
  'seated-dumbbell-press': 3,
  'standing-military-press': 3,
  'machine-shoulder-military-press': 3,
  'barbell-shoulder-press': 2,
  'arnold-dumbbell-press': 2,
  'leverage-shoulder-press': 2,
  'seated-barbell-military-press': 2,
  'smith-machine-overhead-shoulder-press': 1,
  'two-arm-kettlebell-military-press': 1,
  'shoulder-press-with-bands': 1,
  'standing-palms-in-dumbbell-press': 1,
  // Aperturas y fondos
  'cable-crossover': 3,
  butterfly: 3,
  'dumbbell-flyes': 2,
  'incline-dumbbell-flyes': 2,
  'low-cable-crossover': 2,
  'incline-cable-flye': 1,
  'flat-bench-cable-flyes': 1,
  'dips-triceps-version': 2,
  'dips-chest-version': 2,
  'bench-dips': 2,
  'dip-machine': 2,
  'parallel-bar-dip': 1,
  // Tracción horizontal
  'bent-over-barbell-row': 3,
  'one-arm-dumbbell-row': 3,
  'seated-cable-rows': 3,
  'dumbbell-incline-row': 3,
  'inverted-row': 3,
  't-bar-row-with-handle': 2,
  'bent-over-two-dumbbell-row': 2,
  'leverage-iso-row': 2,
  'seated-one-arm-cable-pulley-rows': 2,
  'leverage-high-row': 1,
  'one-arm-kettlebell-row': 1,
  'reverse-grip-bent-over-rows': 1,
  'lying-t-bar-row': 1,
  'elevated-cable-rows': 1,
  // Tracción vertical
  pullups: 3,
  'wide-grip-lat-pulldown': 3,
  'chin-up': 3,
  'close-grip-front-lat-pulldown': 2,
  'v-bar-pulldown': 2,
  'underhand-cable-pulldowns': 2,
  'band-assisted-pull-up': 2,
  'straight-arm-pulldown': 2,
  'weighted-pull-ups': 1,
  'one-arm-lat-pulldown': 1,
  'rope-straight-arm-pulldown': 1,
  'full-range-of-motion-lat-pulldown': 1,
  'straight-arm-dumbbell-pullover': 2,
  'bent-arm-dumbbell-pullover': 1,
  // Hombro y trapecio
  'side-lateral-raise': 3,
  'cable-seated-lateral-raise': 2,
  'seated-side-lateral-raise': 2,
  'lateral-raise-with-bands': 2,
  'standing-low-pulley-deltoid-raise': 2,
  'one-arm-side-laterals': 1,
  'front-dumbbell-raise': 2,
  'front-cable-raise': 1,
  'front-plate-raise': 1,
  'face-pull': 3,
  'reverse-machine-flyes': 3,
  'band-pull-apart': 3,
  'reverse-flyes': 2,
  'cable-rear-delt-fly': 2,
  'seated-bent-over-rear-delt-raise': 2,
  'back-flyes-with-bands': 2,
  'bent-over-dumbbell-rear-delt-raise-with-head-on-bench': 2,
  'external-rotation-with-band': 1,
  'external-rotation-with-cable': 1,
  'dumbbell-shrug': 3,
  'barbell-shrug': 2,
  'cable-shrugs': 1,
  // Bíceps
  'barbell-curl': 3,
  'dumbbell-bicep-curl': 3,
  'hammer-curls': 3,
  'ez-bar-curl': 3,
  'incline-dumbbell-curl': 2,
  'preacher-curl': 2,
  'standing-biceps-cable-curl': 2,
  'concentration-curls': 2,
  'cable-hammer-curls-rope-attachment': 2,
  'dumbbell-alternate-bicep-curl': 2,
  'machine-bicep-curl': 1,
  'alternate-hammer-curl': 1,
  'spider-curl': 1,
  'zottman-curl': 1,
  'machine-preacher-curls': 1,
  // Tríceps
  'triceps-pushdown': 3,
  'triceps-pushdown-rope-attachment': 3,
  'cable-rope-overhead-triceps-extension': 3,
  'ez-bar-skullcrusher': 2,
  'standing-dumbbell-triceps-extension': 2,
  'tricep-dumbbell-kickback': 2,
  'machine-triceps-extension': 2,
  'triceps-pushdown-v-bar-attachment': 2,
  'lying-triceps-press': 1,
  'dumbbell-one-arm-triceps-extension': 1,
  // Core
  'cable-crunch': 3,
  'hanging-leg-raise': 3,
  'reverse-crunch': 3,
  crunches: 2,
  'ab-crunch-machine': 2,
  'flat-bench-lying-leg-raise': 2,
  'knee-hip-raise-on-parallel-bars': 2,
  'air-bike': 2,
  'exercise-ball-crunch': 1,
  'decline-crunch': 1,
  plank: 3,
  'dead-bug': 3,
  'ab-roller': 2,
  'barbell-ab-rollout-on-knees': 2,
  'exercise-ball-pull-in': 1,
  'pallof-press': 3,
  'pallof-press-with-rotation': 2,
  'standing-cable-wood-chop': 2,
  'russian-twist': 2,
  'side-bridge': 3,
  'dumbbell-side-bend': 1,
  'farmers-walk': 2,
  // Antebrazo
  'seated-dumbbell-palms-up-wrist-curl': 1,
  'seated-dumbbell-palms-down-wrist-curl': 1,
  // Cardio para acondicionamiento
  'bicycling-stationary': 3,
  'elliptical-trainer': 3,
  'walking-treadmill': 3,
  'recumbent-bike': 2,
  'rowing-stationary': 2,
  stairmaster: 2,
  'jogging-treadmill': 2,
  'running-treadmill': 1,
  'rope-jumping': 1,
}

/**
 * Variantes que nunca se programan por defecto (quedan en la biblioteca): resistencia acomodada
 * con bandas o cadenas, técnicas de competición, trayectorias de riesgo para el hombro o el cuello
 * y ejercicios con material que casi nadie tiene.
 */
export const NOT_PROGRAMMABLE =
  /\bchains?\b|with bands|reverse band|guillotine|neck press|\bspeed\b|board press|pin press|behind (the )?neck|bradford|rocky|jefferson|zercher|kipping|partials|one arm chin|single-arm push-up|isometric|plyo|\bjump|clock push|side to side chins|gironda|london bridges|rope climb|\bsled\b|body-up|anti-gravity|see-?saw|suspended|renegade|wipers|muscle[- ]up|deficit|off pins|hanging bar|manual|towel|slam|gorilla/i

export interface ExerciseOverride {
  pattern?: Pattern
  level?: Level
  equipment?: Equipment[]
  primaryMuscles?: Muscle[]
  secondaryMuscles?: Muscle[]
  jointStress?: Partial<Record<InjuryZone, StressLevel>>
  unilateral?: boolean
}

/** Correcciones puntuales que las reglas no pueden deducir del nombre. */
export const OVERRIDES: Record<string, ExerciseOverride> = {
  'flutter-kicks': { pattern: 'coreFlexion', primaryMuscles: ['abs'], secondaryMuscles: ['quads'] },
  'cable-iron-cross': { pattern: 'chestFly' },
  'floor-glute-ham-raise': { pattern: 'kneeFlexion' },
  plank: { jointStress: { lowerBack: 'low', shoulder: 'low' } },
  'dead-bug': { jointStress: { lowerBack: 'low' } },
  'side-bridge': { unilateral: true, jointStress: { lowerBack: 'low', shoulder: 'moderate' } },
  'farmers-walk': {
    equipment: ['dumbbell'],
    level: 'beginner',
    jointStress: { lowerBack: 'moderate' },
  },
  'goblet-squat': { equipment: ['dumbbell'] },
  'pull-through': { equipment: ['cable'] },
  'inverted-row': {
    equipment: ['barbell', 'rack'],
    jointStress: { lowerBack: 'low', shoulder: 'low', elbow: 'low' },
  },
  'band-assisted-pull-up': { equipment: ['bands', 'pullupBar'] },
  'hanging-leg-raise': { equipment: ['pullupBar'], level: 'intermediate' },
  'knee-hip-raise-on-parallel-bars': { equipment: ['dipStation'] },
  'butt-lift-bridge': { jointStress: { hip: 'low', lowerBack: 'low', knee: 'low' } },
  'leg-press': { jointStress: { knee: 'moderate', hip: 'moderate', lowerBack: 'moderate' } },
  'barbell-hip-thrust': { equipment: ['barbell', 'bench'], level: 'beginner' },
  // El banco de hiperextensiones es material de gimnasio: se trata como máquina.
  'hyperextensions-back-extensions': { equipment: ['machine'] },
  'walking-treadmill': { equipment: ['machine'], jointStress: { knee: 'low', ankle: 'low' } },
  'bicycling-stationary': { equipment: ['machine'] },
  'elliptical-trainer': { equipment: ['machine'], level: 'beginner' },
  'recumbent-bike': { equipment: ['machine'] },
  'rowing-stationary': { equipment: ['machine'], level: 'beginner' },
  stairmaster: { equipment: ['machine'], level: 'beginner' },
  'jogging-treadmill': { equipment: ['machine'] },
  'running-treadmill': { equipment: ['machine'] },

  // Clasificación: casos que las reglas por nombre no resuelven bien.
  'balance-board': { pattern: 'other', jointStress: { ankle: 'moderate', knee: 'low' } },
  'car-drivers': {
    pattern: 'frontRaise',
    primaryMuscles: ['frontDelts'],
    secondaryMuscles: ['sideDelts', 'forearms'],
  },
  'single-dumbbell-raise': {
    pattern: 'frontRaise',
    primaryMuscles: ['frontDelts'],
    secondaryMuscles: ['sideDelts', 'traps'],
  },
  'alternating-deltoid-raise': { secondaryMuscles: ['frontDelts'] },
  // Es un remo al mentón abierto con mancuernas.
  'dumbbell-raise': {
    pattern: 'lateralRaise',
    primaryMuscles: ['sideDelts'],
    secondaryMuscles: ['traps'],
    jointStress: { shoulder: 'high' },
  },
  'bent-over-low-pulley-side-lateral': {
    pattern: 'rearDelt',
    primaryMuscles: ['rearDelts'],
    secondaryMuscles: ['upperBack', 'traps'],
    jointStress: { shoulder: 'low', lowerBack: 'moderate' },
  },
  'cuban-press': {
    pattern: 'rearDelt',
    primaryMuscles: ['rearDelts'],
    secondaryMuscles: ['sideDelts', 'traps'],
    jointStress: { shoulder: 'moderate', elbow: 'low' },
  },
  'kettlebell-thruster': {
    pattern: 'other',
    primaryMuscles: ['quads', 'frontDelts'],
    secondaryMuscles: ['glutes', 'triceps', 'sideDelts'],
    jointStress: { knee: 'moderate', hip: 'moderate', shoulder: 'high', lowerBack: 'moderate' },
  },
  // Tumbado boca abajo, la elevación «lateral» trabaja el deltoides posterior.
  'lying-one-arm-lateral-raise': {
    pattern: 'rearDelt',
    primaryMuscles: ['rearDelts'],
    secondaryMuscles: ['upperBack'],
    jointStress: { shoulder: 'low' },
  },
  'cable-hip-adduction': { primaryMuscles: ['adductors'], secondaryMuscles: [] },
  // Jalones con brazos rectos: extensión de hombro (patrón de pullover), no tracción vertical.
  'straight-arm-pulldown': { pattern: 'pullover', jointStress: { elbow: 'low' } },
  'rope-straight-arm-pulldown': { pattern: 'pullover', jointStress: { elbow: 'low' } },
  'cable-incline-pushdown': { pattern: 'pullover', jointStress: { elbow: 'low' } },
  'snatch-pull': { pattern: 'olympic' },
  'squat-jerk': { pattern: 'olympic' },
  'freehand-jump-squat': { pattern: 'plyometric' },
  'weighted-jump-squat': { pattern: 'plyometric' },
  'kneeling-jump-squat': { pattern: 'plyometric' },
  'lunge-sprint': { pattern: 'plyometric' },
  'plyo-kettlebell-pushups': { pattern: 'plyometric' },
  'downward-facing-balance': {
    pattern: 'other',
    jointStress: { lowerBack: 'low', wrist: 'moderate' },
  },
  'wind-sprints': {
    equipment: ['pullupBar'],
    jointStress: { shoulder: 'moderate', lowerBack: 'moderate' },
  },
  'dips-chest-version': { equipment: ['dipStation'] },
  'parallel-bar-dip': { equipment: ['dipStation'] },
  'ring-dips': { equipment: ['other'] },
  'smith-incline-shoulder-raise': { equipment: ['bench', 'machine'] },
  'speed-box-squat': { equipment: ['bands', 'barbell', 'box', 'rack'] },
  // Tumbado boca abajo, la elevación con barra al frente es una elevación frontal.
  'straight-raises-on-incline-bench': {
    pattern: 'frontRaise',
    primaryMuscles: ['frontDelts'],
    secondaryMuscles: ['upperBack', 'traps'],
  },
  'neck-press': { jointStress: { shoulder: 'high', neck: 'moderate' } },
  'barbell-guillotine-bench-press': { jointStress: { shoulder: 'high', neck: 'moderate' } },
  // El press con mina (landmine) es de los empujes verticales más amables con el hombro.
  'landmine-linear-jammer': { jointStress: { shoulder: 'moderate' } },
  'single-arm-linear-jammer': { jointStress: { shoulder: 'moderate' } },
  // Estrés articular de básicos (★2-3), que es lo que más pesa en la seguridad de los planes.
  'trap-bar-deadlift': { jointStress: { lowerBack: 'moderate', knee: 'moderate' } },
  'kettlebell-one-legged-deadlift': { jointStress: { lowerBack: 'moderate', ankle: 'moderate' } },
  'bodyweight-walking-lunge': { jointStress: { knee: 'moderate' } },
  // Nivel: el origen etiqueta algunos básicos con más dificultad de la real (o menos).
  'front-barbell-squat': { level: 'intermediate' },
  pullups: { level: 'intermediate' },
  'chin-up': { level: 'intermediate' },
  'dumbbell-shoulder-press': { level: 'beginner' },
  'face-pull': { level: 'beginner' },
  'standing-dumbbell-calf-raise': { level: 'beginner' },
  'dumbbell-rear-lunge': { level: 'beginner' },
  'dumbbell-step-ups': { level: 'beginner' },
  'barbell-glute-bridge': { level: 'beginner' },
  'one-legged-cable-kickback': { level: 'beginner' },
  'seated-one-arm-cable-pulley-rows': { level: 'beginner' },
  'v-bar-pulldown': { level: 'beginner' },
  'seated-bent-over-rear-delt-raise': { level: 'beginner' },
}
